Q9: Go to the link - https://www.myntra.com/shoes
Set Price filter to “Rs. 6649 to Rs. 13099” , Color filter to “Black”, as shown in
the below image
nd then scrape First 100 shoes data you get. The data should include “Brand” of
the shoes , Short Shoe description, price of the shoe as shown in the below image.
Please note that applying the filter and scraping the data , everything should be
done through code only and there should not be any manual step.

In [11]:
#importing necessary modules
import pandas as pd
from urllib.request import Request, urlopen
import requests
from selenium import webdriver
from selenium.webdriver import chrome
from selenium.common.exceptions import *
import datetime
import time

def shoes(url):
    driver = webdriver.Chrome('/home/santosh/Downloads/chromedriver_linux64/chromedriver')
    
    driver.get(url)
    
    driver.maximize_window()
    
    filter1 = driver.find_element_by_xpath("//ul[@class='price-list']/li[2]/label").click()
    
    time.sleep(3)
    
    filter2 = driver.find_element_by_xpath("//li[@class][1]/label").click()
    
    time.sleep(3)
    
    product_name = []
    
    product_desc = []
    
    product_price = []
    
    j = 0
    
    while j < 3:
        
        time.sleep(3)
        
        brands=driver.find_elements_by_xpath("//h3[@class='product-brand']")

        for brand in brands:

            product_name.append(brand.text)
            
        
        descriptions=driver.find_elements_by_xpath("//h4[@class='product-product']")

        for description in descriptions:

            product_desc.append(description.text)
            
        
        
        price = driver.find_elements_by_xpath("//div[@class='product-price']")
        
        for pr in price:
            
            product_price.append(pr.text)
        
        if j == 0:
            
            driver.find_element_by_xpath("//li[@class='pagination-next']").click()
            
        elif j ==1:
            
            driver.find_element_by_xpath("//li[@class='pagination-active']").click()
            
        else:
            
            pass
        j+=1
        
    shoes = pd.DataFrame({})
    
    shoes["Brand"] = product_name[:100]
    
    shoes["Name"] = product_desc[:100]
    
    shoes["Price"] = product_price[:100]
    
    return shoes

    shoes.to_csv("shoes.csv")

In [12]:
shoes("https://www.myntra.com/shoes?")

,Brand,Name,Price
0,Nike,Men JORDAN DELTA Sneakers,Rs. 10995
1,ADIDAS Originals,Men Nite Jogger Fluid Sneakers,Rs. 8449Rs. 12999(35% OFF)
2,PUMA Motorsport,Men Ferrari Race Kart Sneakers,Rs. 7999Rs. 9999(20% OFF)
3,Hush Puppies,Men Solid Leather Formal Slip-Ons,Rs. 8999
4,Nike,Men React Infinity Running,Rs. 11621Rs. 15495(25% OFF)
...,...,...,...
95,Geox,Women Leather Boat Shoes,Rs. 8990
96,Cole Haan,Women Woven Design Sneakers,Rs. 6749Rs. 14999(55% OFF)
97,Ruosh,Men Solid Leather Formal Monks,Rs. 6990
98,Geox,Men Leather Formal Derbys,Rs. 11490
99,Geox,Men Leather Formal Slip-Ons,Rs. 11242Rs. 14990(25% OFF)